CREATE TABLE SALES_TABLE (
    CUSTOMER_NUMBER NUMBER,
    CUSTOMER_NAME VARCHAR2(10),
    QTY NUMBER,
    INVOICE_DATE DATE
);


INSERT INTO SALES_TABLE VALUES (1, 'vrinda mam', 4, TO_DATE('5-oct-25','DD-MON-RR'));
INSERT INTO SALES_TABLE VALUES (2, 'shivani', 4, TO_DATE('10-oct-25','DD-MON-RR'));
INSERT INTO SALES_TABLE VALUES (3, 'prachi', 4, TO_DATE('15-oct-25','DD-MON-RR'));
INSERT INTO SALES_TABLE VALUES (7, 'abhay', 4, TO_DATE('5-sep-25','DD-MON-RR'));
INSERT INTO SALES_TABLE VALUES (6, 'saurabh', 4, TO_DATE('5-jan-25','DD-MON-RR'));

COMMIT;

select * from SALES_TABLE;

CREATE TABLE customer_test1 (
    CUSTOMER_NUMBER NUMBER,
    CUSTOMER_NAME VARCHAR2(10),
    PERIOD VARCHAR2(10)
);
DECLARE
    
    V_RECORD customer_test1%ROWTYPE;
    
    CURSOR C1 IS
        SELECT DISTINCT CUSTOMER_NUMBER,
                        CUSTOMER_NAME,
                        TO_CHAR(INVOICE_DATE,'MON-YY') AS PERIOD
        FROM SALES_TABLE
        WHERE INVOICE_DATE > TO_DATE('01-OCT-25','DD-MON-RR');
BEGIN
    OPEN C1;
    LOOP
        FETCH C1 INTO V_RECORD;
        EXIT WHEN C1%NOTFOUND;

        INSERT INTO customer_test1 (CUSTOMER_NUMBER, CUSTOMER_NAME, PERIOD)
        VALUES (V_RECORD.CUSTOMER_NUMBER, V_RECORD.CUSTOMER_NAME, V_RECORD.PERIOD);
    END LOOP;
    CLOSE C1;

    COMMIT;
END;
/


SELECT * FROM customer_test1;
